#!/bin/bash

sudo apt-get update
sudo apt-get install -y \
   bc \
   gdb \
   libopenblas-dev \
   libncurses-dev \
   m4 \
   make \
   nano \
   netcat-traditional \
   ninja-build \
   python3-dev \
   python3-venv \
   vim \
   wget \
   xz-utils
python3 -m venv _build
source _build/bin/activate
pip install -r shared/rocroller/requirements.txt
