#!/bin/bash

cd $(git rev-parse --show-toplevel)

git sparse-checkout init --cone

git sparse-checkout set \
    shared/rocroller \
    shared/mxdatagenerator \
    .vscode

git sparse-checkout reapply
